name: injective
version: v0.2.12

chains:
  - id: injective-1
    name: injective
    numValidators: 2
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    resources:
      cpu: "0.2"
      memory: "200M"
  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
    resources:
      cpu: "0.2"
      memory: "200M"

relayers:
  - name: injective-cosmos
    type: hermes
    replicas: 1
    chains:
      - injective-1
      - cosmoshub-4
    resources:
      cpu: "0.1"
      memory: "100M"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"

faucet:
  resources:
    cpu: "0.1"
    memory: "100M"
