name: injective
version: v0.2.12

chains:
  - id: injective-1
    name: injective
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007

  - id: cosmoshub-4
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: injective-cosmos
    type: hermes
    replicas: 1
    chains:
      - injective-1
      - cosmoshub-4

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
