name: Run Tests Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          cache: false

      - name: Install Dependencies
        run: |
          echo "YARN_ENABLE_IMMUTABLE_INSTALLS=false" >> $GITHUB_ENV
          npm install -g create-interchain-app

      - name: ibc-asset-list
        run: |
          cia --example ibc-asset-list --name ibc-asset-list
          cd ibc-asset-list
          yarn build

      - name: vote-proposal
        run: |
          cia --example vote-proposal --name vote-proposal
          cd vote-proposal
          yarn build

      - name: ibc-transfer
        run: |
          cia --example ibc-transfer --name ibc-transfer
          cd ibc-transfer
          yarn build

      - name: swap-tokens
        run: |
          cia --example swap-tokens --name swap-tokens
          cd swap-tokens
          yarn build

      - name: provide-liquidity
        run: |
          cia --example provide-liquidity --name provide-liquidity
          cd provide-liquidity
          yarn build

      - name: nft
        run: |
          cia --example nft --name nft
          cd nft
          touch yarn.lock
          yarn install
          yarn build

      - name: authz
        run: |
          cia --example authz --name authz
          cd authz
          yarn build

      - name: connect-chain
        run: |
          cia --template connect-chain --name connect-chain
          cd connect-chain
          yarn build

      - name: connect-multi-chain
        run: |
          cia --template connect-multi-chain --name connect-multi-chain
          cd connect-multi-chain
          yarn build

      - name: website
        run: |
          cia --boilerplate website --name website
          cd website
          yarn build
