name: Run Tests Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Dependencies
        run: |
          npm install -g create-interchain-app

      - name: authz
        run: |
          cia --example authz --name authz
          cd authz
          pnpm build

      - name: ibc-asset-list
        run: |
          cia --example ibc-asset-list --name ibc-asset-list
          cd ibc-asset-list
          pnpm build

      - name: injective
        run: |
          cia --example injective --name injective
          cd injective
          pnpm build

      - name: injective-vue
        run: |
          cia --example injective-vue --name injective-vue
          cd injective-vue
          pnpm build

      - name: stake-tokens
        run: |
          cia --example stake-tokens --name stake-tokens
          cd stake-tokens
          pnpm build

      - name: vote-proposal
        run: |
          cia --example vote-proposal --name vote-proposal
          cd vote-proposal
          pnpm build

      - name: chain-template
        run: |
          cia --template chain-template --name chain-template
          cd chain-template
          pnpm build

      - name: connect-chain
        run: |
          cia --template connect-chain --name connect-chain
          cd connect-chain
          pnpm build

      - name: connect-multi-chain
        run: |
          cia --template connect-multi-chain --name connect-multi-chain
          cd connect-multi-chain
          pnpm build

      - name: website
        run: |
          cia --boilerplate website --name website
          cd website
          pnpm build
